### ISSUE TITLE
Internal Server Error When Posting Venue

### ISSUE THREAD

**Issue by MarcMouallem** [lmucs/wutup#6] opened 2012-12-08 05:50 UTC
curl -i -X POST -H 'Content-type:application/json' -d '{"name":"Loyola Marymount University","address":"6238 Hollywood Boulevard  Los Angeles, CA 90028"}' http://localhost:8080/wutup/venues

is returning an internal server error!?

**Comment by SaymV** [comment] 2012-12-08 05:57
Idk I've been making venues for a couple weeks.

**Comment by rtoal** [comment] 2012-12-08 06:02
@Sam are you posting to /wutup/venues to create venues?  I've reproduced the error.  Do you include latitude and longitude in your JSON?

**Comment by tnichols89** [comment] 2012-12-08 06:34
Should be fixed. The fix is kind of sloppy... it's at the resource level for now. I'll clean it up and make it more legit then push it again. Works for me now, though. Let me know if it gives you guys any beef.

**Comment by MarcMouallem** [comment] 2012-12-08 06:35
Thanks Tyler!

**Closed as completed** 2012-12-08 07:14 UTC
Labels: bug
